{
 "title": "Leetcode_data_analyzer",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "最熱門的10個題目（依Likes數量）",
   "type": "barchart",
   "description": "用途：直觀看到最受歡迎的題目。",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \"Title\", \"Likes\"\r\nFROM mydata\r\nORDER BY \"Likes\" DESC\r\nLIMIT 10;"
    }
   ]
  },
  {
   "title": "提供 Solution 和 Video Solution 的題目比例",
   "type": "stat",
   "description": "用途：清楚看出有無提供解答和影片解答的比例。",
   "gridPos": { "h": 5, "w": 9, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n  COUNT(*) FILTER (WHERE \"HasSolution\" = TRUE) AS 有解答,\r\n  COUNT(*) FILTER (WHERE \"HasVideoSolution\" = TRUE) AS 提供影片解答,\r\n  COUNT(*) AS 總題數\r\nFROM mydata;"
    }
   ]
  },
  {
   "title": "難度與平均喜歡率(Likes Ratio)關係分析",
   "type": "barchart",
   "description": "用途：分析不同難度題目的平均喜愛程度。",
   "gridPos": { "h": 6, "w": 9, "x": 12, "y": 5 },
   "targets": [
    {
     "rawSql": "SELECT \r\n  \"Difficulty\", \r\n  ROUND((AVG(\"Likes_ratio\") * 100)::numeric, 2) AS avg_likes_ratio_percent\r\nFROM \r\n  mydata\r\nGROUP BY \r\n  \"Difficulty\"\r\nORDER BY \r\n  avg_likes_ratio_percent DESC;"
    }
   ]
  },
  {
   "title": "討論區留言數量最多的前10題",
   "type": "barchart",
   "description": "用途：找出引起最多討論的題目。",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT \"Title\", \"Number of Discussion\"\r\nFROM mydata\r\nORDER BY \"Number of Discussion\" DESC\r\nLIMIT 10;"
    }
   ]
  },
  {
   "title": "平均提交次數(Submission)與難度的關係",
   "type": "barchart",
   "description": "用途：呈現不同難度題目使用者平均嘗試次數，反映題目難度與使用者嘗試間的關聯。",
   "gridPos": { "h": 9, "w": 9, "x": 12, "y": 11 },
   "targets": [
    {
     "rawSql": "SELECT \"Difficulty\", ROUND(AVG(\"Submission\"),0) AS avg_submissions\r\nFROM mydata\r\nGROUP BY \"Difficulty\"\r\nORDER BY avg_submissions DESC;"
    }
   ]
  },
  {
   "title": "Acceptance Rate 最高的前10題",
   "type": "table",
   "description": "用途：顯示最容易通過的題目。",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT \"Title\", \"Acceptance Rate\"\r\nFROM mydata\r\nORDER BY \"Acceptance Rate\" DESC\r\nLIMIT 10;"
    }
   ]
  },
  {
   "title": "難度（Difficulty）分佈",
   "type": "piechart",
   "description": "用途：分析不同難度的題目分佈。",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \"Difficulty\", COUNT(*) AS total_count\r\nFROM mydata\r\nGROUP BY \"Difficulty\"\r\nORDER BY total_count DESC;"
    }
   ]
  }
 ]
}